# Generated by Django 5.0.3 on 2024-03-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_email', models.EmailField(max_length=254)),
                ('publisher_name', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Something',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some_column', models.BooleanField(verbose_name=True)),
            ],
        ),
    ]
